version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE=${DATABASE}
        - DB_URL=${DB_URL}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - FRONT_CLIENT=${FRONT_CLIENT}
        - SECRET=${SECRET}
